version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered prebuild status"
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean install
  post_build:
    commands:
    - echo "Entered post build phase"
artifacts:
  files:
    - target/spring-aws-elastic-bean-stack-1.0.2-SNAPSHOT.jar
